version: '3.1'
services:
  database:
    image: postgres
    ports:
      - '15432:5432'
    volumes:
      - ./Calories_Bot:/docker-entrypoint-initdb.d
      - database:/data/database
    environment:
      - 'POSTGRES_USER=postgres'
      - 'POSTGRES_DB=database'
      - 'POSTGRES_PASSWORD=qwerty'
volumes:
  database:
    driver: local