create table users
(
    first_name              varchar(80) default 'Unnamed'::character varying,
    registration_date       timestamp(6) not null,
    action                  varchar(30),
    current_notification_id uuid,
    chat_id                 bigint,
    id                      uuid         not null
        constraint users_pk
            primary key,
    current_product_uuid    uuid
);

alter table users
    owner to postgres;




create table products
(
    id                 integer generated by default as identity
        constraint products_pk
            primary key,
    product_name       varchar(80) not null
        constraint unique_product_name
            unique,
    protein_value      double precision,
    fat_value          double precision,
    carbohydrate_value double precision,
    kcal_value         integer
);

alter table products
    owner to postgres;

create index products_product_name_index
    on products (product_name);




create table notifications
(
    title       varchar(50),
    description varchar(60),
    status      varchar(8),
    seconds     integer,
    id          uuid not null
        constraint notifications_pk
            primary key,
    user_id     uuid
        constraint fk9y21adhxn0ayjhfocscqox7bh
            references users
);

alter table notifications
    owner to postgres;




create table users_notifications
(
    user_id          uuid not null
        constraint fkil3tssmpyic5ruavb9jbbw2bb
            references users,
    notifications_id uuid not null
        constraint uk_fqai0p0e0nsyh9pp2j0h32ggq
            unique
        constraint fk17pt2krtfgoof65xdvtbpf5aw
            references notifications,
    primary key (user_id, notifications_id)
);

alter table users_notifications
    owner to postgres;




create table users_products
(
    product_id    integer
        constraint users_products___fk2
            references products,
    id            uuid not null
        primary key,
    status        varchar(8),
    user_id       uuid
        constraint users_products__id_fk
            references users,
    product_grams integer,
    eating_time   timestamp
);

alter table users_products
    owner to postgres;

create index users_products_product_id_index
    on users_products (product_id);

