package telegram.Calories_Bot.entity.enums;

public enum Action {
    NONE,
    SENDING_TITLE, SENDING_DESCRIPTION, SENDING_TIME,
    SENDING_PRODUCT_NAME, SENDING_PRODUCT_GRAM, SENDING_PRODUCT_PERIOD;
}

